
revision-item-updater:
  # 手持物品时检查物品更新
  item-held: true

common:
  true: '§a是'
  false: '§c否'
  on: '§a开'
  off: '§c关'
  none: '§c无'

types:
  SWORD: Sword
  DAGGER: Dagger
  SPEAR: Spear
  HAMMER: Hammer
  GAUNTLET: Gauntlet
  WHIP: Whip
  STAFF: Staff
  BOW: Bow
  CROSSBOW: Crossbow
  MUSKET: Musket
  LUTE: Lute
  TOOL: Tool
  CATALYST: Catalyst
  OFF_CATALYST: Catalyst (Off hand)
  MAIN_CATALYST: Catalyst (Main hand)
  ORNAMENT: Ornament
  ARMOR: Armor
  CONSUMABLE: Consumable
  MISCELLANEOUS: Miscellaneous
  GEM_STONE: Gem Stone
  SKIN: Skin
  ACCESSORY: Accessory
  BLOCK: Block
