name: Development Build

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '*.md'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '*.md'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v6
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6
      - name: Set up Java
        uses: actions/setup-java@v6
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Build Plugin
        run: ./gradlew clean build
      - name: Upload Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: MMOi18n
          path: out/*.jar
          if-no-files-found: error
